### ISSUE TITLE
Embedded software structure 

### ISSUE THREAD

**Issue by echtbrecht** [echtbrecht/press_play#7]
Quite a broad "issue": our esp32's need software to enable our business logic: we can write this ourselves or we can look for examples online.

I am can only write arduino code in one file (quite unstructured) and am looking forward to learn from you pro's how to structure a project like this.

What IDE to use (Arduino, VS Code,...)? What language to use? How to include dependencies?

**Comment by seppycool** [comment]
We can use the same system that is used with the M5 sticks but I don't know if this is usefull.

**Comment by seppycool** [comment]
If not we need to write the complete code on the ESP32. That can be done with VS code. Because it need to be a real time device we should use RTOS. This made it easy to check the buttons, send data and do other stuff in real time

**Comment by echtbrecht** [comment]
Do you have experience with setting up a RTOS project? I tried to start up one project a year ago, but the options are so big that I returned empty handed back to the "simple" Arduino IDE.

**Comment by seppycool** [comment]
I have made some programs with FreeRTOS. This with buttons that are tracked in real time and also a project with wifi. So maybe when I combine the two I got a kind of prototype. I look tomorrow if I find this on my computer
